# Generated by Django 5.2.7 on 2025-10-31 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_nurse_alter_appointment_doctor_and_more'),
        ('medical_record', '0003_medicalrecord_nurse_alter_medicalrecord_patient'),
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescribed_by',
        ),
        migrations.AddField(
            model_name='prescription',
            name='medical_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='medical_record.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='appointment.appointment'),
        ),
    ]
