# Generated by Django 5.2.7 on 2025-10-31 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_initial'),
        ('medical_record', '0002_initial'),
        ('patient', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.nurse'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient.patient'),
        ),
    ]
